### ISSUE TITLE
import in non-package

### ISSUE THREAD

**Issue by vanucci** [thelazyliz/reply-bot#1]
Hi im trying to run this code, i have created the bot_details.py but when i try to run the bot i get this error 

```
Traceback (most recent call last):
  File "testechteambot.0.0.1.py", line 30, in <module>
    from .bot_details import get_botID, get_serverURL
ValueError: Attempted relative import in non-package

```

**Comment by thelazyliz** [comment]
probably too late for me to reply, but in case others are wondering: 

you need to create bot_details.py, which I didn't commit to this repo. this contains the bot key you received from botfather, as well as the URL that you've set up for webhooks.

for local development purposes you can use something like ngrok to expose your local server. if you're not familiar with webhooks, you can check out the telepot docs for long polling. 

def get_botID(bot_name):
    if bot_name == '<YOUR_BOT_NAME>':
        return '<YOUR_BOT_KEY>'

def get_serverURL():
    return "<YOUR_SERVER_URL>"
